### ISSUE TITLE
[1.7] Rebuild models

### ISSUE THREAD

**Issue by DarkGuardsman** [BuiltBrokenModding/Atomic-Science#6]
Convert current models from techne to .obj
- [ ] Centrifuge
- [ ] Fission Reactor
- [ ] Reactor Turbine
- [ ] Nuclear Boiler
- [ ] Fusion Reactor
- [ ] Chemical Extractor

**Comment by DarkGuardsman** [comment]
https://drive.google.com/drive/folders/1amY3pd1ZfR63Ifs0yWm28qfw5zYXOUHH?usp=sharing
That is everything I have, already converted them to .obj. Now, they only need to be fixed to remove extra faces and clean up z-fighting.

**Comment by ttamttamS** [comment]
I'm sharing a folder where I'm putting complete stuff. All I have right now is the centrifuge, if it's to your satisfaction I'll go ahead and do the rest.

**Comment by DarkGuardsman** [comment]
I assume its the "complete" folder and the model uploaded at 1:45am. From what I can see it doesn't look like much changed. The idea of rebuilding the models is to fix overlap of parts. As well parent parts to each other that are connected. This is a bit of lengthy process as it involves basically redoing the model. As part will need to be cut, merged, faces connected, and UVs rebuilt.

**Comment by ttamttamS** [comment]
Yes, all I did was remove hidden faces and fix areas with Z-fighting. Completly removing overlap and making the whole thing as more or less a single mesh would indeed take a while for the reasons you gave, especially since I'm not very familiar with UV mapping yet.
I'll see what I can do before finals kick in.
